"""FastAPI dependency: require valid API Key for webhook endpoints. Reject if missing or invalid."""
from fastapi import Header, HTTPException, Request, status


def get_api_key_from_request(request: Request) -> str:
    """Extract API key from X-API-Key header or Authorization: Bearer <key>."""
    api_key = request.headers.get("X-API-Key")
    if api_key:
        return api_key.strip()
    auth = request.headers.get("Authorization")
    if auth and auth.strip().lower().startswith("bearer "):
        return auth.strip().split(maxsplit=1)[1]
    return ""


async def require_api_key(request: Request) -> str:
    """
    Dependency: require valid API key. Reject with 401 if missing or not issued by this system.
    Accepts: X-API-Key header or Authorization: Bearer <key>
    """
    from app.api_keys import validate_api_key

    api_key = get_api_key_from_request(request)
    if not api_key:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing API key. Provide X-API-Key header or Authorization: Bearer <key>",
            headers={"WWW-Authenticate": "ApiKey"},
        )
    if not validate_api_key(api_key):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Invalid or unauthorized API key. Only keys generated by this system are accepted.",
        )
    return api_key
